[settings]
server="https://libki.myserver.com"
name="MyPrintManager"
api_key="NotActuallyAnApiKey"
;customHeaderName="X-Libki-Token"     ; Optional. If set, every request sent to the Libki server will include this HTTP header.
;customHeaderValue="secret-value"     ; Optional.
